Repository borglab/gtsfm, pull requests merged in 2021-08, with the labels that each got.

#219 fixed view_scene() AssertionError bug
  gtsfm/common/gtsfm_data.py
  gtsfm/utils/io.py
Labels: bug

#228 Move some functions from scene_optimizer and multiview_optimizer to utils
  gtsfm/multi_view_optimizer.py
  gtsfm/scene_optimizer.py
  gtsfm/utils/graph.py
  gtsfm/utils/viz.py
Labels: refactor

#242 Remove underconstrained TA square unit test
  tests/averaging/translation/test_averaging_1dsfm.py
Labels: quick
