Repository borglab/gtsfm, pull requests merged in 2021-12, with the labels that each got.

#225 Adding 2-view Bundle adjustment post verification
  gtsfm/bundle/bundle_adjustment.py
  gtsfm/configs/deep_front_end.yaml
  gtsfm/configs/scene_optimizer_unit_test_config.yaml
  gtsfm/configs/sift_front_end.yaml
  gtsfm/evaluation/metrics.py
  gtsfm/frontend/inlier_support_processor.py
  gtsfm/scene_optimizer.py
  gtsfm/two_view_estimator.py
  gtsfm/utils/metrics.py
  tests/test_two_view_estimator.py
Labels: objective

#405 Add `max_keypoints` to config
  gtsfm/configs/deep_front_end.yaml
  gtsfm/configs/sift_front_end.yaml
  gtsfm/frontend/detector_descriptor/superpoint.py
Labels: quick

#243 Correctly handle GtsfmMetric for data array with all NaN entries
  gtsfm/evaluation/metrics.py
  tests/evaluation/metrics_test.py
Labels: bug, quick
